import json
from pathlib import Path
from typing import Optional

from pydantic import BaseModel, Field

from agent.tools import ToolRegistry
from proxy.models import ProxyEntry
from proxy.pool import ProxyPool


DEFAULT_OUTPUT = Path(__file__).parent.parent / "data" / "proxychains.conf"


def _proxy_to_conf_line(proxy: ProxyEntry) -> str:
    """Convert a ProxyEntry to a proxychains.conf line."""
    # Format: <type> <host> <port> [user] [pass]
    proto_map = {
        "http": "http",
        "https": "http",
        "socks4": "socks4",
        "socks5": "socks5",
    }
    ptype = proto_map.get(proxy.protocol.value, "http")
    line = f"{ptype}\t{proxy.host}\t{proxy.port}"
    if proxy.username:
        line += f"\t{proxy.username}"
        if proxy.password:
            line += f"\t{proxy.password}"
    return line


def _build_conf(
    proxies: list[ProxyEntry],
    chain_type: str = "dynamic_chain",
    proxy_dns: bool = True,
    tcp_read_timeout: int = 15000,
    tcp_connect_timeout: int = 8000,
    quiet_mode: bool = False,
) -> str:
    """Generate a full proxychains.conf file content."""
    lines = [
        "# ProxyChains Configuration",
        "# Generated by RedAgent",
        "#",
        f"# Chain type: {chain_type}",
        f"# Proxies: {len(proxies)}",
        "",
        "# Chain mode",
    ]

    # Chain type — only one can be active
    for ct in ["strict_chain", "dynamic_chain", "random_chain"]:
        if ct == chain_type:
            lines.append(ct)
        else:
            lines.append(f"# {ct}")

    lines.extend([
        "",
        "# Proxy DNS requests - no DNS leak",
        f"{'proxy_dns' if proxy_dns else '# proxy_dns'}",
        "",
        "# Timeouts",
        f"tcp_read_time_out {tcp_read_timeout}",
        f"tcp_connect_time_out {tcp_connect_timeout}",
    ])

    if quiet_mode:
        lines.append("")
        lines.append("quiet_mode")

    lines.extend([
        "",
        "[ProxyList]",
        "# type\thost\tport\t[user]\t[pass]",
    ])

    for proxy in proxies:
        lines.append(_proxy_to_conf_line(proxy))

    return "\n".join(lines) + "\n"


# --- Tool parameter models ---

class GenerateConfParams(BaseModel):
    chain_type: str = Field(
        default="dynamic_chain",
        description="Chain type: strict_chain, dynamic_chain, or random_chain"
    )
    proxy_dns: bool = Field(default=True, description="Route DNS through the proxy chain (prevents DNS leaks)")
    alive_only: bool = Field(default=True, description="Only include alive proxies")
    protocol: Optional[str] = Field(default=None, description="Filter by protocol")
    country: Optional[str] = Field(default=None, description="Filter by country code")
    max_proxies: int = Field(default=0, description="Maximum proxies to include (0 = all)")
    output_path: Optional[str] = Field(default=None, description="Custom output file path (default: data/proxychains.conf)")
    tcp_read_timeout: int = Field(default=15000, description="TCP read timeout in ms")
    tcp_connect_timeout: int = Field(default=8000, description="TCP connect timeout in ms")
    quiet_mode: bool = Field(default=False, description="Enable quiet mode (suppress output)")


class SetChainTypeParams(BaseModel):
    chain_type: str = Field(description="Chain type: strict_chain, dynamic_chain, or random_chain")


class ExportChainParams(BaseModel):
    chain_proxy_ids: list[str] = Field(description="Ordered list of proxy IDs forming the chain")
    chain_type: str = Field(default="strict_chain", description="Chain type for the export")
    proxy_dns: bool = Field(default=True, description="Route DNS through chain")
    output_path: Optional[str] = Field(default=None, description="Custom output file path")


class GenerateAndApplyParams(BaseModel):
    chain_proxy_ids: list[str] = Field(description="Ordered list of proxy IDs forming the chain")
    proxy_dns: bool = Field(default=True, description="Route DNS through chain")
    timeout: int = Field(default=30, description="Default timeout for proxied requests in seconds")


# --- Tool registration ---

def register_proxychains_tools(registry: ToolRegistry):

    @registry.register(
        name="generate_proxychains_conf",
        description="Generate a proxychains.conf file from the proxy pool. Supports filtering and all chain modes.",
        parameters_model=GenerateConfParams,
    )
    def generate_proxychains_conf(
        chain_type: str = "dynamic_chain",
        proxy_dns: bool = True,
        alive_only: bool = True,
        protocol: str | None = None,
        country: str | None = None,
        max_proxies: int = 0,
        output_path: str | None = None,
        tcp_read_timeout: int = 15000,
        tcp_connect_timeout: int = 8000,
        quiet_mode: bool = False,
    ) -> dict:
        pool = ProxyPool.load()
        proxies = pool.find(protocol=protocol, country=country, alive_only=alive_only)

        if not proxies:
            return {"status": "no_proxies", "message": "No proxies match the filters."}

        # Sort by latency
        proxies.sort(key=lambda p: p.latency_ms or float("inf"))

        if max_proxies > 0:
            proxies = proxies[:max_proxies]

        conf_content = _build_conf(
            proxies=proxies,
            chain_type=chain_type,
            proxy_dns=proxy_dns,
            tcp_read_timeout=tcp_read_timeout,
            tcp_connect_timeout=tcp_connect_timeout,
            quiet_mode=quiet_mode,
        )

        out = Path(output_path) if output_path else DEFAULT_OUTPUT
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(conf_content, encoding="utf-8")

        return {
            "status": "generated",
            "output_path": str(out.resolve()),
            "chain_type": chain_type,
            "proxy_count": len(proxies),
            "proxy_dns": proxy_dns,
            "config_preview": conf_content[:500],
        }

    @registry.register(
        name="set_chain_type",
        description="Update the chain type in the existing proxychains.conf file.",
        parameters_model=SetChainTypeParams,
    )
    def set_chain_type(chain_type: str) -> dict:
        valid = {"strict_chain", "dynamic_chain", "random_chain"}
        if chain_type not in valid:
            return {"status": "error", "message": f"Invalid chain type. Must be one of: {', '.join(valid)}"}

        if not DEFAULT_OUTPUT.exists():
            return {"status": "error", "message": "No proxychains.conf found. Generate one first."}

        content = DEFAULT_OUTPUT.read_text(encoding="utf-8")

        # Comment out all chain types, then uncomment the selected one
        for ct in valid:
            content = content.replace(f"\n{ct}\n", f"\n# {ct}\n")
            content = content.replace(f"\n{ct}", f"\n# {ct}")

        content = content.replace(f"# {chain_type}", chain_type)

        DEFAULT_OUTPUT.write_text(content, encoding="utf-8")

        return {
            "status": "updated",
            "chain_type": chain_type,
            "file": str(DEFAULT_OUTPUT.resolve()),
        }

    @registry.register(
        name="export_chain",
        description="Export a specific proxy chain (list of proxy IDs) to a proxychains.conf file.",
        parameters_model=ExportChainParams,
    )
    def export_chain(
        chain_proxy_ids: list[str],
        chain_type: str = "strict_chain",
        proxy_dns: bool = True,
        output_path: str | None = None,
    ) -> dict:
        pool = ProxyPool.load()
        proxies = []
        missing = []

        for pid in chain_proxy_ids:
            proxy = pool.get_by_id(pid)
            if proxy:
                proxies.append(proxy)
            else:
                missing.append(pid)

        if missing:
            return {
                "status": "error",
                "message": f"Proxy IDs not found: {', '.join(missing)}",
            }

        if not proxies:
            return {"status": "error", "message": "No proxies to export."}

        conf_content = _build_conf(
            proxies=proxies,
            chain_type=chain_type,
            proxy_dns=proxy_dns,
        )

        out = Path(output_path) if output_path else DEFAULT_OUTPUT
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(conf_content, encoding="utf-8")

        return {
            "status": "exported",
            "output_path": str(out.resolve()),
            "chain_type": chain_type,
            "hops": len(proxies),
            "chain": [p.to_display_dict() for p in proxies],
            "config_preview": conf_content,
        }

    @registry.register(
        name="generate_and_apply_chain",
        description=(
            "Generate a proxychains.conf file from a list of proxy IDs AND set it as the active config "
            "for built-in proxy execution. Combines export_chain + apply_proxy_config in one step."
        ),
        parameters_model=GenerateAndApplyParams,
    )
    def generate_and_apply_chain(
        chain_proxy_ids: list[str],
        proxy_dns: bool = True,
        timeout: int = 30,
    ) -> dict:
        # Export the conf file
        export_result = export_chain(chain_proxy_ids=chain_proxy_ids, proxy_dns=proxy_dns)
        if export_result.get("status") == "error":
            return export_result

        # Apply as active config
        from proxy.active_config import ActiveConfig, ChainMode
        mode = ChainMode.SINGLE if len(chain_proxy_ids) == 1 else ChainMode.CHAIN
        config = ActiveConfig(
            mode=mode,
            proxy_ids=chain_proxy_ids,
            proxy_dns=proxy_dns,
            timeout=timeout,
        )
        config.save()

        export_result["active_config"] = "applied"
        export_result["message"] = (
            f"Chain exported to proxychains.conf AND applied as active config. "
            f"All proxy_fetch/proxy_curl calls now route through this {len(chain_proxy_ids)}-hop chain."
        )
        return export_result
